package goal.money.providerdemo.mapper;

import goal.money.providerdemo.dto.DetailInfo;
import org.apache.ibatis.annotations.Param;

public interface DetailInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail_info
     *
     * @mbg.generated
     */
    int insert(DetailInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail_info
     *
     * @mbg.generated
     */
    int insertSelective(DetailInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail_info
     *
     * @mbg.generated
     */
    DetailInfo selectByPrimaryKey(Long detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DetailInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DetailInfo record);

    DetailInfo queryDetailByPhoneAndProductId(@Param("phone") String phone, @Param("productId")long productId);

    void updateBuyQuantity(@Param("phone") String phone,@Param("productId")long productId,@Param("buyQuantity")int buyQuantity);
}