package goal.money.providerdemo.mapper;

import goal.money.providerdemo.dto.OrderInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated
     */
    int insert(OrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated
     */
    int insertSelective(OrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated
     */
    OrderInfo selectByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderInfo record);

    void insertIntoOrder(OrderInfo orderInfo);

    int querySumProductQuantity(String phone);

    int querySumPrice(String phone);

    List<OrderInfo> queryOrderByState(@Param("phone") String phone,@Param("orderState") int orderState
            ,@Param("startPage")int startPage,@Param("pageSize")int pageSize);

    List<OrderInfo> queryOrderByNo(@Param("phone") String phone,@Param("orderState") String orderNumber,@Param("orderState")int orderState);

    List<OrderInfo> queryOrderByName(@Param("phone") String phone,@Param("orderState") String productName,@Param("orderState")int orderState);


}