package goal.money.providerdemo.mapper;

import goal.money.providerdemo.dto.ProductInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProductInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated
     */
    int insert(ProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated
     */
    int insertSelective(ProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated
     */
    ProductInfo selectByPrimaryKey(Long productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductInfo record);

    ProductInfo selectGoods(Long productId);

    int queryQuantity(Long productId);

    ProductInfo queryProductByNameAndColor(String productName,String productColor);

    List<ProductInfo> queryProductListByName(@Param("productName") String productName,@Param("productCategory") String productCategory);

    List<ProductInfo>  showIndexProductList(@Param("productCategory")String productCategory,@Param("startPage")int startPage,@Param("pageSize")int pageSize);

    ProductInfo defaultProduct();
}