package goal.money.providerdemo.mapper;

import goal.money.providerdemo.dto.RecycleInfo;

public interface RecycleInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recycle_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long recycleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recycle_info
     *
     * @mbg.generated
     */
    int insert(RecycleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recycle_info
     *
     * @mbg.generated
     */
    int insertSelective(RecycleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recycle_info
     *
     * @mbg.generated
     */
    RecycleInfo selectByPrimaryKey(Long recycleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recycle_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RecycleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recycle_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RecycleInfo record);
}