package goal.money.providerdemo.mapper;

import goal.money.providerdemo.dto.Recycle;

public interface RecycleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recycle
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long recycleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recycle
     *
     * @mbg.generated
     */
    int insert(Recycle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recycle
     *
     * @mbg.generated
     */
    int insertSelective(Recycle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recycle
     *
     * @mbg.generated
     */
    Recycle selectByPrimaryKey(Long recycleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recycle
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Recycle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recycle
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Recycle record);
}