package goal.money.providerdemo.dto;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cart_info
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class CartInfo implements Serializable {
    private static final long serialVersionUID = -7762682121676903285L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_info.cart_id
     *
     * @mbg.generated
     */
    private Long cartId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_info.product_id
     *
     * @mbg.generated
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_info.buy_quantity
     *
     * @mbg.generated
     */
    private Integer buyQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_info.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_info.price
     *
     * @mbg.generated
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_info.ip
     *
     * @mbg.generated
     */
    private String ip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_info.cart_id
     *
     * @return the value of cart_info.cart_id
     *
     * @mbg.generated
     */
    public Long getCartId() {
        return cartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_info.cart_id
     *
     * @param cartId the value for cart_info.cart_id
     *
     * @mbg.generated
     */
    public void setCartId(Long cartId) {
        this.cartId = cartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_info.product_id
     *
     * @return the value of cart_info.product_id
     *
     * @mbg.generated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_info.product_id
     *
     * @param productId the value for cart_info.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_info.buy_quantity
     *
     * @return the value of cart_info.buy_quantity
     *
     * @mbg.generated
     */
    public Integer getBuyQuantity() {
        return buyQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_info.buy_quantity
     *
     * @param buyQuantity the value for cart_info.buy_quantity
     *
     * @mbg.generated
     */
    public void setBuyQuantity(Integer buyQuantity) {
        this.buyQuantity = buyQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_info.phone
     *
     * @return the value of cart_info.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_info.phone
     *
     * @param phone the value for cart_info.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_info.price
     *
     * @return the value of cart_info.price
     *
     * @mbg.generated
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_info.price
     *
     * @param price the value for cart_info.price
     *
     * @mbg.generated
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_info.ip
     *
     * @return the value of cart_info.ip
     *
     * @mbg.generated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_info.ip
     *
     * @param ip the value for cart_info.ip
     *
     * @mbg.generated
     */
    public void setIp(String ip) {
        this.ip = ip;
    }
}