package goal.money.providerdemo.dto;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cart_info
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class CartInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_info.cart_id
     *
     * @mbg.generated
     */
    private Long cartId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_info.product_id
     *
     * @mbg.generated
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_info.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_info.product_price
     *
     * @mbg.generated
     */
    private Integer productPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_info.buy_quantity
     *
     * @mbg.generated
     */
    private Integer buyQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_info.product_describe
     *
     * @mbg.generated
     */
    private String productDescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_info.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_info.product_color
     *
     * @mbg.generated
     */
    private String productColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_info.phone
     *
     * @mbg.generated
     */
    private Integer phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_info.price_multiply _quantity
     *
     * @mbg.generated
     */
    private Integer priceMultiplyQuantity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_info.cart_id
     *
     * @return the value of cart_info.cart_id
     *
     * @mbg.generated
     */
    public Long getCartId() {
        return cartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_info.cart_id
     *
     * @param cartId the value for cart_info.cart_id
     *
     * @mbg.generated
     */
    public void setCartId(Long cartId) {
        this.cartId = cartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_info.product_id
     *
     * @return the value of cart_info.product_id
     *
     * @mbg.generated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_info.product_id
     *
     * @param productId the value for cart_info.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_info.product_name
     *
     * @return the value of cart_info.product_name
     *
     * @mbg.generated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_info.product_name
     *
     * @param productName the value for cart_info.product_name
     *
     * @mbg.generated
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_info.product_price
     *
     * @return the value of cart_info.product_price
     *
     * @mbg.generated
     */
    public Integer getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_info.product_price
     *
     * @param productPrice the value for cart_info.product_price
     *
     * @mbg.generated
     */
    public void setProductPrice(Integer productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_info.buy_quantity
     *
     * @return the value of cart_info.buy_quantity
     *
     * @mbg.generated
     */
    public Integer getBuyQuantity() {
        return buyQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_info.buy_quantity
     *
     * @param buyQuantity the value for cart_info.buy_quantity
     *
     * @mbg.generated
     */
    public void setBuyQuantity(Integer buyQuantity) {
        this.buyQuantity = buyQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_info.product_describe
     *
     * @return the value of cart_info.product_describe
     *
     * @mbg.generated
     */
    public String getProductDescribe() {
        return productDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_info.product_describe
     *
     * @param productDescribe the value for cart_info.product_describe
     *
     * @mbg.generated
     */
    public void setProductDescribe(String productDescribe) {
        this.productDescribe = productDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_info.user_id
     *
     * @return the value of cart_info.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_info.user_id
     *
     * @param userId the value for cart_info.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_info.product_color
     *
     * @return the value of cart_info.product_color
     *
     * @mbg.generated
     */
    public String getProductColor() {
        return productColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_info.product_color
     *
     * @param productColor the value for cart_info.product_color
     *
     * @mbg.generated
     */
    public void setProductColor(String productColor) {
        this.productColor = productColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_info.phone
     *
     * @return the value of cart_info.phone
     *
     * @mbg.generated
     */
    public Integer getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_info.phone
     *
     * @param phone the value for cart_info.phone
     *
     * @mbg.generated
     */
    public void setPhone(Integer phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_info.price_multiply _quantity
     *
     * @return the value of cart_info.price_multiply _quantity
     *
     * @mbg.generated
     */
    public Integer getPriceMultiplyQuantity() {
        return priceMultiplyQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_info.price_multiply _quantity
     *
     * @param priceMultiplyQuantity the value for cart_info.price_multiply _quantity
     *
     * @mbg.generated
     */
    public void setPriceMultiplyQuantity(Integer priceMultiplyQuantity) {
        this.priceMultiplyQuantity = priceMultiplyQuantity;
    }
}