package goal.money.providerdemo.dto;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table order_info
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class OrderInfo implements Serializable {
    private static final long serialVersionUID = -1817153753772692464L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_id
     *
     * @mbg.generated
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.productid
     *
     * @mbg.generated
     */
    private Long productid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_number
     *
     * @mbg.generated
     */
    private String orderNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.delivery_user_name
     *
     * @mbg.generated
     */
    private String deliveryUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.delivery_user_phone
     *
     * @mbg.generated
     */
    private String deliveryUserPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.delivery_user_address
     *
     * @mbg.generated
     */
    private String deliveryUserAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_status
     *
     * @mbg.generated
     */
    private Integer orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.buy_quantity
     *
     * @mbg.generated
     */
    private Integer buyQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.gain_score
     *
     * @mbg.generated
     */
    private Integer gainScore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_id
     *
     * @return the value of order_info.order_id
     *
     * @mbg.generated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_id
     *
     * @param orderId the value for order_info.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.productid
     *
     * @return the value of order_info.productid
     *
     * @mbg.generated
     */
    public Long getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.productid
     *
     * @param productid the value for order_info.productid
     *
     * @mbg.generated
     */
    public void setProductid(Long productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_number
     *
     * @return the value of order_info.order_number
     *
     * @mbg.generated
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_number
     *
     * @param orderNumber the value for order_info.order_number
     *
     * @mbg.generated
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.phone
     *
     * @return the value of order_info.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.phone
     *
     * @param phone the value for order_info.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.delivery_user_name
     *
     * @return the value of order_info.delivery_user_name
     *
     * @mbg.generated
     */
    public String getDeliveryUserName() {
        return deliveryUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.delivery_user_name
     *
     * @param deliveryUserName the value for order_info.delivery_user_name
     *
     * @mbg.generated
     */
    public void setDeliveryUserName(String deliveryUserName) {
        this.deliveryUserName = deliveryUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.delivery_user_phone
     *
     * @return the value of order_info.delivery_user_phone
     *
     * @mbg.generated
     */
    public String getDeliveryUserPhone() {
        return deliveryUserPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.delivery_user_phone
     *
     * @param deliveryUserPhone the value for order_info.delivery_user_phone
     *
     * @mbg.generated
     */
    public void setDeliveryUserPhone(String deliveryUserPhone) {
        this.deliveryUserPhone = deliveryUserPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.delivery_user_address
     *
     * @return the value of order_info.delivery_user_address
     *
     * @mbg.generated
     */
    public String getDeliveryUserAddress() {
        return deliveryUserAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.delivery_user_address
     *
     * @param deliveryUserAddress the value for order_info.delivery_user_address
     *
     * @mbg.generated
     */
    public void setDeliveryUserAddress(String deliveryUserAddress) {
        this.deliveryUserAddress = deliveryUserAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_status
     *
     * @return the value of order_info.order_status
     *
     * @mbg.generated
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_status
     *
     * @param orderStatus the value for order_info.order_status
     *
     * @mbg.generated
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.buy_quantity
     *
     * @return the value of order_info.buy_quantity
     *
     * @mbg.generated
     */
    public Integer getBuyQuantity() {
        return buyQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.buy_quantity
     *
     * @param buyQuantity the value for order_info.buy_quantity
     *
     * @mbg.generated
     */
    public void setBuyQuantity(Integer buyQuantity) {
        this.buyQuantity = buyQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.gain_score
     *
     * @return the value of order_info.gain_score
     *
     * @mbg.generated
     */
    public Integer getGainScore() {
        return gainScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.gain_score
     *
     * @param gainScore the value for order_info.gain_score
     *
     * @mbg.generated
     */
    public void setGainScore(Integer gainScore) {
        this.gainScore = gainScore;
    }
}