package goal.money.providerdemo.dto;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table product_info
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ProductInfo implements Serializable {
    private static final long serialVersionUID = -5664941049640938999L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_id
     *
     * @mbg.generated
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.sale_quantity
     *
     * @mbg.generated
     */
    private Long saleQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.listing_time
     *
     * @mbg.generated
     */
    private Long listingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_describe
     *
     * @mbg.generated
     */
    private String productDescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_quantity
     *
     * @mbg.generated
     */
    private Long productQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_price
     *
     * @mbg.generated
     */
    private Integer productPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_category
     *
     * @mbg.generated
     */
    private Integer productCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_color
     *
     * @mbg.generated
     */
    private String productColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_img
     *
     * @mbg.generated
     */
    private String productImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_score
     *
     * @mbg.generated
     */
    private Integer productScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.good_rate
     *
     * @mbg.generated
     */
    private Double goodRate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_id
     *
     * @return the value of product_info.product_id
     *
     * @mbg.generated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_id
     *
     * @param productId the value for product_info.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.sale_quantity
     *
     * @return the value of product_info.sale_quantity
     *
     * @mbg.generated
     */
    public Long getSaleQuantity() {
        return saleQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.sale_quantity
     *
     * @param saleQuantity the value for product_info.sale_quantity
     *
     * @mbg.generated
     */
    public void setSaleQuantity(Long saleQuantity) {
        this.saleQuantity = saleQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_name
     *
     * @return the value of product_info.product_name
     *
     * @mbg.generated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_name
     *
     * @param productName the value for product_info.product_name
     *
     * @mbg.generated
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.listing_time
     *
     * @return the value of product_info.listing_time
     *
     * @mbg.generated
     */
    public Long getListingTime() {
        return listingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.listing_time
     *
     * @param listingTime the value for product_info.listing_time
     *
     * @mbg.generated
     */
    public void setListingTime(Long listingTime) {
        this.listingTime = listingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_describe
     *
     * @return the value of product_info.product_describe
     *
     * @mbg.generated
     */
    public String getProductDescribe() {
        return productDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_describe
     *
     * @param productDescribe the value for product_info.product_describe
     *
     * @mbg.generated
     */
    public void setProductDescribe(String productDescribe) {
        this.productDescribe = productDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_quantity
     *
     * @return the value of product_info.product_quantity
     *
     * @mbg.generated
     */
    public Long getProductQuantity() {
        return productQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_quantity
     *
     * @param productQuantity the value for product_info.product_quantity
     *
     * @mbg.generated
     */
    public void setProductQuantity(Long productQuantity) {
        this.productQuantity = productQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_price
     *
     * @return the value of product_info.product_price
     *
     * @mbg.generated
     */
    public Integer getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_price
     *
     * @param productPrice the value for product_info.product_price
     *
     * @mbg.generated
     */
    public void setProductPrice(Integer productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_category
     *
     * @return the value of product_info.product_category
     *
     * @mbg.generated
     */
    public Integer getProductCategory() {
        return productCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_category
     *
     * @param productCategory the value for product_info.product_category
     *
     * @mbg.generated
     */
    public void setProductCategory(Integer productCategory) {
        this.productCategory = productCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_color
     *
     * @return the value of product_info.product_color
     *
     * @mbg.generated
     */
    public String getProductColor() {
        return productColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_color
     *
     * @param productColor the value for product_info.product_color
     *
     * @mbg.generated
     */
    public void setProductColor(String productColor) {
        this.productColor = productColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_img
     *
     * @return the value of product_info.product_img
     *
     * @mbg.generated
     */
    public String getProductImg() {
        return productImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_img
     *
     * @param productImg the value for product_info.product_img
     *
     * @mbg.generated
     */
    public void setProductImg(String productImg) {
        this.productImg = productImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_score
     *
     * @return the value of product_info.product_score
     *
     * @mbg.generated
     */
    public Integer getProductScore() {
        return productScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_score
     *
     * @param productScore the value for product_info.product_score
     *
     * @mbg.generated
     */
    public void setProductScore(Integer productScore) {
        this.productScore = productScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.good_rate
     *
     * @return the value of product_info.good_rate
     *
     * @mbg.generated
     */
    public Double getGoodRate() {
        return goodRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.good_rate
     *
     * @param goodRate the value for product_info.good_rate
     *
     * @mbg.generated
     */
    public void setGoodRate(Double goodRate) {
        this.goodRate = goodRate;
    }

    private int startPage;
    private int  pageSize;


    public int getStartPage() {

        return startPage;
    }

    public void setStartPage(int startPage) {
        int i=1;
        if (startPage>=i){
            this.startPage = (startPage-1)*pageSize;
        }else {
            this.startPage=0;
        }
        this.startPage=startPage;
    }

    public int getPageSize() {
        return pageSize;
    }

    public void setPageSize(int pageSize) {
        this.pageSize = pageSize;
    }

}