package goal.money.providerdemo.dto;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_info
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class UserInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.openid
     *
     * @mbg.generated
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.nickname
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.language
     *
     * @mbg.generated
     */
    private String language;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.headimgurl
     *
     * @mbg.generated
     */
    private String headimgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.accumulate_point
     *
     * @mbg.generated
     */
    private Integer accumulatePoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.experience
     *
     * @mbg.generated
     */
    private Integer experience;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.experience_level
     *
     * @mbg.generated
     */
    private Integer experienceLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_level
     *
     * @mbg.generated
     */
    private Integer userLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_birth
     *
     * @mbg.generated
     */
    private Long userBirth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.birth_is_update
     *
     * @mbg.generated
     */
    private Integer birthIsUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_id
     *
     * @return the value of user_info.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_id
     *
     * @param userId the value for user_info.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.phone
     *
     * @return the value of user_info.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.phone
     *
     * @param phone the value for user_info.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.password
     *
     * @return the value of user_info.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.password
     *
     * @param password the value for user_info.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.openid
     *
     * @return the value of user_info.openid
     *
     * @mbg.generated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.openid
     *
     * @param openid the value for user_info.openid
     *
     * @mbg.generated
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.nickname
     *
     * @return the value of user_info.nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.nickname
     *
     * @param nickname the value for user_info.nickname
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.sex
     *
     * @return the value of user_info.sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.sex
     *
     * @param sex the value for user_info.sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.language
     *
     * @return the value of user_info.language
     *
     * @mbg.generated
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.language
     *
     * @param language the value for user_info.language
     *
     * @mbg.generated
     */
    public void setLanguage(String language) {
        this.language = language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.city
     *
     * @return the value of user_info.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.city
     *
     * @param city the value for user_info.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.province
     *
     * @return the value of user_info.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.province
     *
     * @param province the value for user_info.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.headimgurl
     *
     * @return the value of user_info.headimgurl
     *
     * @mbg.generated
     */
    public String getHeadimgurl() {
        return headimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.headimgurl
     *
     * @param headimgurl the value for user_info.headimgurl
     *
     * @mbg.generated
     */
    public void setHeadimgurl(String headimgurl) {
        this.headimgurl = headimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.accumulate_point
     *
     * @return the value of user_info.accumulate_point
     *
     * @mbg.generated
     */
    public Integer getAccumulatePoint() {
        return accumulatePoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.accumulate_point
     *
     * @param accumulatePoint the value for user_info.accumulate_point
     *
     * @mbg.generated
     */
    public void setAccumulatePoint(Integer accumulatePoint) {
        this.accumulatePoint = accumulatePoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.experience
     *
     * @return the value of user_info.experience
     *
     * @mbg.generated
     */
    public Integer getExperience() {
        return experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.experience
     *
     * @param experience the value for user_info.experience
     *
     * @mbg.generated
     */
    public void setExperience(Integer experience) {
        this.experience = experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.experience_level
     *
     * @return the value of user_info.experience_level
     *
     * @mbg.generated
     */
    public Integer getExperienceLevel() {
        return experienceLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.experience_level
     *
     * @param experienceLevel the value for user_info.experience_level
     *
     * @mbg.generated
     */
    public void setExperienceLevel(Integer experienceLevel) {
        this.experienceLevel = experienceLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_level
     *
     * @return the value of user_info.user_level
     *
     * @mbg.generated
     */
    public Integer getUserLevel() {
        return userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_level
     *
     * @param userLevel the value for user_info.user_level
     *
     * @mbg.generated
     */
    public void setUserLevel(Integer userLevel) {
        this.userLevel = userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_birth
     *
     * @return the value of user_info.user_birth
     *
     * @mbg.generated
     */
    public Long getUserBirth() {
        return userBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_birth
     *
     * @param userBirth the value for user_info.user_birth
     *
     * @mbg.generated
     */
    public void setUserBirth(Long userBirth) {
        this.userBirth = userBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.birth_is_update
     *
     * @return the value of user_info.birth_is_update
     *
     * @mbg.generated
     */
    public Integer getBirthIsUpdate() {
        return birthIsUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.birth_is_update
     *
     * @param birthIsUpdate the value for user_info.birth_is_update
     *
     * @mbg.generated
     */
    public void setBirthIsUpdate(Integer birthIsUpdate) {
        this.birthIsUpdate = birthIsUpdate;
    }
}